[project]
name = "uv-doc-zh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-llmstxt>=0.2.0",
    "mkdocs-material>=9.6.15",
    "mkdocs-redirects>=1.2.2",
    "mkdocs-static-i18n>=1.3.0",
]
