name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install dependencies
        run: uv sync
      - name: Build and deploy site
        run: uv run mkdocs gh-deploy --force
        env:
          UV_ANALYTICS_PROVIDER: ${{ secrets.ANALYTICS_PROVIDER }}
          UV_GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
          UV_CLARITY_PROJECT_ID: ${{ secrets.CLARITY_PROJECT_ID }}
          PROD: true
